name: Deploy infrastructure from Vultr Instance (Terraform Plan & Apply)

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Terraform plan
    runs-on: ubuntu-latest
    permissions: write-all
    env: 
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Login to Vultr Instance and run terraform plan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_INSTANCE_IP }}
          username: ${{ secrets.VULTR_INSTANCE_USER }}
          key: ${{ secrets.VULTR_INSTANCE_KEY }}
          script: |
            export TF_VAR_database_endpoint=${{ secrets.secrets.DATABASE_HOST }}
            export TF_VAR_database_username=${{ secrets.DATABASE_USERNAME }}
            export TF_VAR_database_password=${{ secrets.DATABASE_PASSWORD }}
            export TF_VAR_database_port=${{ secrets.DATABASE_PORT }}


      - name: Add the infratag
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 1
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/vInfraVer-${{github.run_number}}',
              sha: context.sha
            })
