name: Deploy infrastructure from Vultr Instance (Terraform Plan & Apply)

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Terraform plan
    runs-on: ubuntu-latest
    env: 
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Login to Vultr Instance and run terraform plan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_INSTANCE_IP }}
          username: ${{ secrets.VULTR_INSTANCE_USER }}
          key: ${{ secrets.VULTR_INSTANCE_KEY }}
          script: |
            cd cloudwatch-logs-vue/
            git pull
            terraform init
            terraform plan -out=${RUN_NUMBER}.tfplan
            cat $RUN_NUMBER.tfplan