name: Deploy infrastructure from Vultr Instance (Terraform Plan & Apply)

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Terraform plan
    runs-on: ubuntu-latest
    env: 
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Login to Vultr Instance and run terraform plan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_INSTANCE_IP }}
          username: ${{ secrets.VULTR_INSTANCE_USER }}
          key: ${{ secrets.VULTR_INSTANCE_KEY }}
          script: |
            cd cloudwatch-mock
            git pull
            terraform init
            terraform plan -out=plan-${{ github.run_number }}.out
            terraform show -json plan-${{ github.run_number }}.out > plan-${{ github.run_number }}.json
            terraform apply -auto-approve plan-${{ github.run_number }}.out 
      - name: Add the infratag
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/InfraTag_${{github.run_number}}',
              sha: context.sha
            })
